// ABOUTME: Parser for session_stats.md file format
// ABOUTME: Handles reading and parsing CSV rows with static file header

import fs from 'fs';
import type { StatsFile, StatsFileTotals, SessionRow } from '../types/index.js';

export const CSV_HEADER = 'session_id,project,event,timestamp,model,duration,claude_time,cost,tokens,flags,machine_id';

export const FILE_HEADER = `# Session Statistics
# Generated by cc-session-track plugin
# https://github.com/keithmackay/cc-session-track
# Run /session_stats to see aggregated statistics
`;

/**
 * Parse session_stats.md file into structured data
 * Totals are computed dynamically from rows, not stored in file
 */
export function parseStatsFile(filePath: string): StatsFile {
  if (!fs.existsSync(filePath)) {
    return {
      totals: createEmptyTotals(),
      rows: []
    };
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.trim().split('\n');

  // Find CSV header line to determine where data starts
  const headerIndex = lines.findIndex(line => line.startsWith('session_id,'));
  if (headerIndex === -1) {
    return {
      totals: createEmptyTotals(),
      rows: []
    };
  }

  const rows: SessionRow[] = [];
  for (let i = headerIndex + 1; i < lines.length; i++) {
    if (lines[i].trim() && !lines[i].startsWith('#')) {
      const row = parseCSVRow(lines[i]);
      if (row) rows.push(row);
    }
  }

  // Compute totals dynamically from rows
  const totals = computeTotals(rows);

  return { totals, rows };
}

/**
 * Find the most recent START row for a given session ID
 */
export function findStartRow(filePath: string, sessionId: string): SessionRow | null {
  const stats = parseStatsFile(filePath);
  const startRows = stats.rows.filter(r =>
    r.sessionId === sessionId && r.event === 'START'
  );
  return startRows[startRows.length - 1] || null;
}

/**
 * Create empty totals object for new stats files
 */
export function createEmptyTotals(): StatsFileTotals {
  return {
    sessions: 0,
    totalDuration: '00:00:00',
    totalClaudeTime: '00:00:00',
    totalCost: 0,
    totalTokens: 0
  };
}

/**
 * Parse a single CSV row into a SessionRow
 */
export function parseCSVRow(line: string): SessionRow | null {
  const parts = line.split(',');
  if (parts.length < 10) return null;

  return {
    sessionId: parts[0],
    project: parts[1],
    event: parts[2] as 'START' | 'END',
    timestamp: parts[3],
    model: parts[4] || null,
    duration: parts[5] || null,
    claudeTime: parts[6] || null,
    cost: parts[7] ? parseFloat(parts[7]) : null,
    tokens: parts[8] ? parseInt(parts[8], 10) : null,
    flags: parts[9] || null,
    machineId: parts[10] || null
  };
}

/**
 * Compute totals from rows (called on read, not stored in file)
 */
function computeTotals(rows: SessionRow[]): StatsFileTotals {
  const endRows = rows.filter(r => r.event === 'END');

  let totalDurationMs = 0;
  let totalClaudeMs = 0;
  let totalCost = 0;
  let totalTokens = 0;

  for (const row of endRows) {
    if (row.duration) totalDurationMs += parseTimeToMs(row.duration);
    if (row.claudeTime) totalClaudeMs += parseTimeToMs(row.claudeTime);
    if (row.cost !== null) totalCost += row.cost;
    if (row.tokens !== null) totalTokens += row.tokens;
  }

  return {
    sessions: endRows.length,
    totalDuration: formatMsToTime(totalDurationMs),
    totalClaudeTime: formatMsToTime(totalClaudeMs),
    totalCost,
    totalTokens
  };
}

/**
 * Parse HH:MM:SS time string to milliseconds
 */
function parseTimeToMs(time: string): number {
  const parts = time.split(':').map(Number);
  if (parts.length === 3) {
    return (parts[0] * 3600 + parts[1] * 60 + parts[2]) * 1000;
  }
  return 0;
}

/**
 * Format milliseconds to HH:MM:SS string
 */
function formatMsToTime(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
}
