import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { parseStatsFile, findStartRow, FILE_HEADER, CSV_HEADER } from '../../src/lib/stats-parser.js';
import { writeStatsFile, appendRow } from '../../src/lib/stats-writer.js';
import type { SessionRow } from '../../src/types/index.js';

describe('stats-file', () => {
  let testDir: string;
  let statsPath: string;

  beforeEach(() => {
    testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-session-track-test-'));
    statsPath = path.join(testDir, 'session_stats.md');
  });

  afterEach(() => {
    fs.rmSync(testDir, { recursive: true, force: true });
  });

  describe('parseStatsFile', () => {
    it('returns empty structure when file does not exist', () => {
      const result = parseStatsFile(statsPath);
      expect(result.totals.sessions).toBe(0);
      expect(result.totals.totalCost).toBe(0);
      expect(result.rows).toHaveLength(0);
    });

    it('parses file with static header and CSV rows', () => {
      const content = `# Session Statistics
# Generated by cc-session-track plugin
# https://github.com/keithmackay/cc-session-track
# Run /session_stats to see aggregated statistics
session_id,project,event,timestamp,model,duration,claude_time,cost,tokens,flags,machine_id
abc123,test-proj,END,2025-01-01T10:30:00Z,claude-sonnet-4,00:30:00,00:05:00,2.50,25000,,user@host`;
      fs.writeFileSync(statsPath, content);

      const result = parseStatsFile(statsPath);
      // Totals computed from END rows
      expect(result.totals.sessions).toBe(1);
      expect(result.totals.totalCost).toBe(2.50);
      expect(result.totals.totalDuration).toBe('00:30:00');
      expect(result.rows).toHaveLength(1);
      expect(result.rows[0].sessionId).toBe('abc123');
      expect(result.rows[0].event).toBe('END');
      expect(result.rows[0].machineId).toBe('user@host');
    });

    it('handles file with multiple rows and computes totals', () => {
      const content = `# Session Statistics
# Generated by cc-session-track plugin
# https://github.com/keithmackay/cc-session-track
# Run /session_stats to see aggregated statistics
session_id,project,event,timestamp,model,duration,claude_time,cost,tokens,flags,machine_id
abc123,test-proj,START,2025-01-01T10:00:00Z,claude-opus-4,,,,,,user@host
abc123,test-proj,END,2025-01-01T10:30:00Z,claude-opus-4,00:30:00,00:05:00,2.50,25000,,user@host
def456,test-proj,START,2025-01-01T11:00:00Z,claude-sonnet-4,,,,,,user@host
def456,test-proj,END,2025-01-01T11:30:00Z,claude-sonnet-4,00:30:00,00:05:00,2.50,25000,,user@host`;
      fs.writeFileSync(statsPath, content);

      const result = parseStatsFile(statsPath);
      expect(result.rows).toHaveLength(4);
      expect(result.totals.sessions).toBe(2);
      expect(result.totals.totalCost).toBe(5.00);
    });
  });

  describe('writeStatsFile', () => {
    it('creates file with static header and CSV data', () => {
      const rows: SessionRow[] = [{
        sessionId: 'abc123',
        project: 'test',
        event: 'END',
        timestamp: '2025-01-01T10:30:00Z',
        model: 'claude-sonnet-4',
        duration: '00:30:00',
        claudeTime: '00:05:00',
        cost: 2.50,
        tokens: 25000,
        flags: null,
        machineId: 'user@host'
      }];

      writeStatsFile(statsPath, rows);

      const content = fs.readFileSync(statsPath, 'utf-8');
      expect(content).toContain('# Session Statistics');
      expect(content).toContain('# Run /session_stats');
      expect(content).toContain('session_id,project,event');
      expect(content).toContain('abc123');
      expect(content).toContain('user@host');
    });
  });

  describe('appendRow', () => {
    it('appends START row to new file', () => {
      const row: SessionRow = {
        sessionId: 'new123',
        project: 'test',
        event: 'START',
        timestamp: '2025-01-01T10:00:00Z',
        model: 'claude-opus-4',
        duration: null,
        claudeTime: null,
        cost: null,
        tokens: null,
        flags: null,
        machineId: 'user@host'
      };

      appendRow(statsPath, row);

      const result = parseStatsFile(statsPath);
      expect(result.rows).toHaveLength(1);
      expect(result.rows[0].event).toBe('START');
      expect(result.rows[0].sessionId).toBe('new123');
      expect(result.rows[0].machineId).toBe('user@host');
    });

    it('computes totals when reading file with END rows', () => {
      // First add a START row
      appendRow(statsPath, {
        sessionId: 'sess1',
        project: 'test',
        event: 'START',
        timestamp: '2025-01-01T10:00:00Z',
        model: 'claude-opus-4',
        duration: null,
        claudeTime: null,
        cost: null,
        tokens: null,
        flags: null,
        machineId: 'user@host'
      });

      // Then add END row with metrics
      appendRow(statsPath, {
        sessionId: 'sess1',
        project: 'test',
        event: 'END',
        timestamp: '2025-01-01T10:30:00Z',
        model: 'claude-opus-4',
        duration: '00:30:00',
        claudeTime: '00:05:00',
        cost: 2.50,
        tokens: 25000,
        flags: null,
        machineId: 'user@host'
      });

      const result = parseStatsFile(statsPath);
      expect(result.totals.sessions).toBe(1);
      expect(result.totals.totalCost).toBe(2.50);
      expect(result.totals.totalTokens).toBe(25000);
    });

    it('accumulates totals across multiple sessions', () => {
      // Session 1
      appendRow(statsPath, {
        sessionId: 's1', project: 'test', event: 'START',
        timestamp: '2025-01-01T10:00:00Z', model: 'claude-opus-4',
        duration: null, claudeTime: null, cost: null, tokens: null, flags: null, machineId: 'user@host'
      });
      appendRow(statsPath, {
        sessionId: 's1', project: 'test', event: 'END',
        timestamp: '2025-01-01T10:30:00Z', model: 'claude-opus-4',
        duration: '00:30:00', claudeTime: '00:05:00', cost: 2.50, tokens: 25000, flags: null, machineId: 'user@host'
      });

      // Session 2
      appendRow(statsPath, {
        sessionId: 's2', project: 'test', event: 'START',
        timestamp: '2025-01-01T11:00:00Z', model: 'claude-sonnet-4',
        duration: null, claudeTime: null, cost: null, tokens: null, flags: null, machineId: 'user@host'
      });
      appendRow(statsPath, {
        sessionId: 's2', project: 'test', event: 'END',
        timestamp: '2025-01-01T12:00:00Z', model: 'claude-sonnet-4',
        duration: '01:00:00', claudeTime: '00:10:00', cost: 5.00, tokens: 50000, flags: null, machineId: 'user@host'
      });

      const result = parseStatsFile(statsPath);
      expect(result.totals.sessions).toBe(2);
      expect(result.totals.totalCost).toBe(7.50);
      expect(result.totals.totalTokens).toBe(75000);
      expect(result.totals.totalDuration).toBe('01:30:00');
    });
  });

  describe('findStartRow', () => {
    it('returns null when no matching start exists', () => {
      const result = findStartRow(statsPath, 'nonexistent');
      expect(result).toBeNull();
    });

    it('finds matching START row by session ID', () => {
      appendRow(statsPath, {
        sessionId: 'target123',
        project: 'test',
        event: 'START',
        timestamp: '2025-01-01T10:00:00Z',
        model: 'claude-opus-4',
        duration: null, claudeTime: null, cost: null, tokens: null, flags: null, machineId: 'user@host'
      });

      const result = findStartRow(statsPath, 'target123');
      expect(result).not.toBeNull();
      expect(result!.sessionId).toBe('target123');
      expect(result!.event).toBe('START');
    });

    it('returns most recent START if multiple exist', () => {
      appendRow(statsPath, {
        sessionId: 'dup', project: 'test', event: 'START',
        timestamp: '2025-01-01T09:00:00Z', model: 'claude-opus-4',
        duration: null, claudeTime: null, cost: null, tokens: null, flags: null, machineId: 'user@host'
      });
      appendRow(statsPath, {
        sessionId: 'dup', project: 'test', event: 'START',
        timestamp: '2025-01-01T10:00:00Z', model: 'claude-sonnet-4',
        duration: null, claudeTime: null, cost: null, tokens: null, flags: null, machineId: 'user@host'
      });

      const result = findStartRow(statsPath, 'dup');
      expect(result!.timestamp).toBe('2025-01-01T10:00:00Z');
      expect(result!.model).toBe('claude-sonnet-4');
    });
  });
});
